### ISSUE TITLE
下载node_module后 npm run dev后报错

### ISSUE THREAD

**Issue by Jaction** [tyaqing/mogo-h5plus#15]
```
[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
/Users/cloverliang/Documents/练习/MogoH5+/mogo-h5plus-master/build/webpack.base.conf.js:48
    ...extraEntry
    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/cloverliang/Documents/练习/MogoH5+/mogo-h5plus-master/build/webpack.dev.conf.js:7:27)
[nodemon] app crashed - waiting for file changes before starting...
```

![image](https://user-images.githubusercontent.com/17811893/43048072-3d013f82-8e14-11e8-82db-f773c4d07067.png)

**Comment by tyaqing** [comment]
应该是解构除了问题
1 检查node是否是最新版本
2 使用npm/yarn安装
