### ISSUE TITLE
浏览器运行报错：plus is not defined

### ISSUE THREAD

**Issue by zhousheng1114** [tyaqing/mogo-h5plus#26]
GET html5plus://ready net::ERR_UNKNOWN_URL_SCHEME
runtime.js?91ec:3 Uncaught (in promise) ReferenceError: plus is not defined
    at eval (runtime.js?91ec:3)
    at F (_export.js?90cd:36)
    at getProperty (runtime.js?91ec:2)
    at VueComponent.created (logo.vue?ad85:25)
    at callHook (vue.esm.js?efeb:2921)
    at VueComponent.Vue._init (vue.esm.js?efeb:4630)
    at new VueComponent (vue.esm.js?efeb:4798)
    at createComponentInstanceForVnode (vue.esm.js?efeb:4310)
    at init (vue.esm.js?efeb:4131)
    at createComponent (vue.esm.js?efeb:5608)
(anonymous) @ runtime.js?91ec:3
F @ _export.js?90cd:36
getProperty @ runtime.js?91ec:2
created @ logo.vue?ad85:25
callHook @ vue.esm.js?efeb:2921
Vue._init @ vue.esm.js?efeb:4630
VueComponent @ vue.esm.js?efeb:4798
createComponentInstanceForVnode @ vue.esm.js?efeb:4310
init @ vue.esm.js?efeb:4131
createComponent @ vue.esm.js?efeb:5608
createElm @ vue.esm.js?efeb:5555
createChildren @ vue.esm.js?efeb:5682
createElm @ vue.esm.js?efeb:5584
createChildren @ vue.esm.js?efeb:5682
createElm @ vue.esm.js?efeb:5584
patch @ vue.esm.js?efeb:6091
Vue._update @ vue.esm.js?efeb:2660
updateComponent @ vue.esm.js?efeb:2788
get @ vue.esm.js?efeb:3142
Watcher @ vue.esm.js?efeb:3131
mountComponent @ vue.esm.js?efeb:2795
Vue.$mount @ vue.esm.js?efeb:8540
Vue.$mount @ vue.esm.js?efeb:10939
init @ vue.esm.js?efeb:4137
createComponent @ vue.esm.js?efeb:5608
createElm @ vue.esm.js?efeb:5555
createChildren @ vue.esm.js?efeb:5682
createElm @ vue.esm.js?efeb:5584
patch @ vue.esm.js?efeb:6091
Vue._update @ vue.esm.js?efeb:2660
updateComponent @ vue.esm.js?efeb:2788
get @ vue.esm.js?efeb:3142
Watcher @ vue.esm.js?efeb:3131
mountComponent @ vue.esm.js?efeb:2795
Vue.$mount @ vue.esm.js?efeb:8540
Vue.$mount @ vue.esm.js?efeb:10939
init @ vue.esm.js?efeb:4137
createComponent @ vue.esm.js?efeb:5608
createElm @ vue.esm.js?efeb:5555
patch @ vue.esm.js?efeb:6130
Vue._update @ vue.esm.js?efeb:2660
updateComponent @ vue.esm.js?efeb:2788
get @ vue.esm.js?efeb:3142
Watcher @ vue.esm.js?efeb:3131
mountComponent @ vue.esm.js?efeb:2795
Vue.$mount @ vue.esm.js?efeb:8540
Vue.$mount @ vue.esm.js?efeb:10939
Vue._init @ vue.esm.js?efeb:4640
Vue @ vue.esm.js?efeb:4729
(anonymous) @ main.js?1c90:45
./src/main.js @ index.js:577
__webpack_require__ @ vue.js:713
fn @ vue.js:118
0 @ index.js:611
__webpack_require__ @ vue.js:713
webpackJsonpCallback @ vue.js:26
(anonymous) @ index.js:1
vconsole.min.js?2f0e:11 [HMR] Waiting for update signal from WDS...
vconsole.min.js?2f0e:11 [Vue warn]: Error in created hook: "ReferenceError: plus is not defined"

found in

---> <App> at src\App.vue
       <Root>
value @ vconsole.min.js?2f0e:11
value @ vconsole.min.js?2f0e:11
value @ vconsole.min.js?2f0e:11
value @ vconsole.min.js?2f0e:11
value @ vconsole.min.js?2f0e:11
value @ vconsole.min.js?2f0e:10
value @ vconsole.min.js?2f0e:10
i @ vconsole.min.js?2f0e:10
vconsole.min.js?2f0e:11 ReferenceError: plus is not defined
    at eval (webpack-internal:///./src/utils/webview.js:71:5)
    at Array.map (native)
    at preLoad (webpack-internal:///./src/utils/webview.js:67:12)
    at VueComponent.created (webpack-internal:///./node_modules/babel-loader/lib/index.js!./node_modules…odules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue:143:77)
    at callHook (webpack-internal:///./node_modules/vue/dist/vue.esm.js:2920:21)
    at VueComponent.Vue._init (webpack-internal:///./node_modules/vue/dist/vue.esm.js:4629:5)
    at new VueComponent (webpack-internal:///./node_modules/vue/dist/vue.esm.js:4797:12)
    at createComponentInstanceForVnode (webpack-internal:///./node_modules/vue/dist/vue.esm.js:4309:10)
    at init (webpack-internal:///./node_modules/vue/dist/vue.esm.js:4130:45)
    at createComponent (webpack-internal:///./node_modules/vue/dist/vue.esm.js:5607:9)

**Comment by tyaqing** [comment]
plus只有在真机上才会生效,在纯网页上是不可以的.请使用真机调试
